AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - db/migrate/*acts_as_taggable_on*
    - bin/**/*
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'config/initializers/secret_token.rb'
    - 'db/seeds.rb'

Rails:
  Enabled: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
