default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: tradernote_development

test:
  <<: *default
  database: tradernote_test

production:
  <<: *default
  database: tradernote_production
